task:
  name: "CartPole-v1"
  num_cells: [80, 120]
client:
  minibatch_size: 128
  n_minibatches: 4
  n_update_epochs: 4
  n_iterations: 10
  gae_gamma: 0.99
  gae_lmbda: 0.95
  clip_grad_norm: 1.0
  lr: 2.5e-4
  normalize_advantage: true
  clip_epsilon: 0.2
server:
  num_rounds: 20
  fraction_fit: 1.0
simulation:
  num_supernodes: 10