# Task configuration for FedDQN with CartPole-v1

task:
  name: "CartPole-v1"
  num_cells: [80, 120]
client:
  minibatch_size: 128
  buffer_size: 10000
  n_iterations: 100
  gamma: 0.99
  lr: 2.5e-4
  clip_grad_norm: 1.0
  target_update_interval: 10
server:
  num_rounds: 20
  fraction_fit: 1.0
simulation:
  num_supernodes: 10
